Found cached dataset yelp_review_full (/home/utsav/.cache/huggingface/datasets/yelp_review_full/yelp_review_full/1.0.0/e8e18e19d7be9e75642fc66b198abadb116f73599ec89a69ba5dd8d1e57ba0bf)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 153.52it/s]
Loading cached shuffled indices for dataset at /home/utsav/.cache/huggingface/datasets/yelp_review_full/yelp_review_full/1.0.0/e8e18e19d7be9e75642fc66b198abadb116f73599ec89a69ba5dd8d1e57ba0bf/cache-b0c3fdb0a0b3a7bb.arrow
Loading cached shuffled indices for dataset at /home/utsav/.cache/huggingface/datasets/yelp_review_full/yelp_review_full/1.0.0/e8e18e19d7be9e75642fc66b198abadb116f73599ec89a69ba5dd8d1e57ba0bf/cache-a0f1bfa2f136ab06.arrow
Converting dataset format to torch for split : train
Converting dataset format to torch for split : test
Adding pad_token to tokenizer
Device : cuda
Traceback (most recent call last):
  File "/home/utsav/representation_learning/embeddings_init/run.py", line 91, in <module>
    BaseModelWithFrozenEmbeddings = ConsolidatedModelClass(
TypeError: __init__() got an unexpected keyword argument 'freeze_pretrained_embeddings'